### ISSUE TITLE
gradle error

### ISSUE THREAD

**Issue by syrius01** [Bort-Millipede/WLT3Serial#1] opened 2017-12-21 07:10 UTC
Hi,

First I would like to thank you for sharing this with the community. I'm getting the following error with gradle:

gradle clean prepare

FAILURE: Build failed with an exception.

* Where:
Build file '/home/sirius/sploits/weblogic/WLT3Serial/build.gradle' line: 12

* What went wrong:
Could not compile build file '/home/sirius/sploits/weblogic/WLT3Serial/build.gradle'.
> startup failed:
  build file '/home/sirius/sploits/weblogic/WLT3Serial/build.gradle': 12: unable to resolve class de.undercouch.gradle.tasks.download.Download
   @ line 12, column 1.
     import de.undercouch.gradle.tasks.download.Download
     ^

  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.326 secs

Any help would be appreciated,

Thanks.

**Comment by Bort-Millipede** [comment] 2017-12-21 18:51
To help me reproduce this issue, can you provide me with the following information: OS version, gradle version, java version, output of "gradle clean prepare --info" command.

The 'de.undercouch.gradle.tasks.download.Download' module is used during the building of WLT3Serial in order to download the latest ysoserial .jar file if the user has not manually placed it in the [PROJECT_DIR]/build/libs directory. I am not sure yet why gradle cannot figure out how to download and import that module into the build process.

Thanks.

**Comment by syrius01** [comment] 2017-12-22 04:36
OS: Ubuntu 14.04.5 LTS

------------------------------------------------------------
Gradle 1.4
------------------------------------------------------------

Gradle build time: Monday, September 9, 2013 8:44:25 o'clock PM UTC
Groovy: 1.8.6
Ant: Apache Ant(TM) version 1.9.3 compiled on April 8 2014
Ivy: non official version
JVM: 1.7.0_121 (Oracle Corporation 24.121-b00)
OS: Linux 3.13.0-107-generic amd64

java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-1ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)

Starting Build
Settings evaluated using empty settings script.
Projects loaded. Root project using build file '/home/sirius/sploits/weblogic/WLT3Serial/build.gradle'.
Included projects: [root project 'WLT3Serial']
Evaluating root project 'WLT3Serial' using build file '/home/sirius/sploits/weblogic/WLT3Serial/build.gradle'.
Compiling build file '/home/sirius/sploits/weblogic/WLT3Serial/build.gradle' using BuildScriptTransformer.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/sirius/sploits/weblogic/WLT3Serial/build.gradle' line: 12

* What went wrong:
Could not compile build file '/home/sirius/sploits/weblogic/WLT3Serial/build.gradle'.
> startup failed:
  build file '/home/sirius/sploits/weblogic/WLT3Serial/build.gradle': 12: unable to resolve class de.undercouch.gradle.tasks.download.Download
   @ line 12, column 1.
     import de.undercouch.gradle.tasks.download.Download
     ^

  1 error


* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 5.212 secs

**Comment by Bort-Millipede** [comment] 2017-12-22 16:52
I believe the problem is you are using an outdated version of gradle (1.4). I downloaded gradle 1.4 and got the same error you are seeing. 

Is there any chance you can upgrade your gradle installation to a newer version? I believe that will fix this issue. I am using gradle 2.10 during development.

**Comment by syrius01** [comment] 2017-12-22 22:30
Yes of course! I will look into it tonight and come back to you as soon as possible if it works with the new version of gradle.

Thanks.

**Comment by syrius01** [comment] 2017-12-24 05:44
I've now upgraded gradle to the latest version available which is on my side: 4.4.1

I re-launched 'gradle clean prepare' and here's the output I'm getting;

sirius@blackb0x:~/sploits/weblogic/WLT3Serial$ gradle clean prepare
Starting a Gradle Daemon (subsequent builds will be faster)
Support for running Gradle using Java 7 has been deprecated and is scheduled to be removed in Gradle 5.0. Please see https://docs.gradle.org/4.4.1/userguide/java_plugin.html#sec:java_cross_compilation for more details.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/sirius/sploits/weblogic/WLT3Serial/build.gradle' line: 2

* What went wrong:
Plugin [id: 'de.undercouch.download', version: '3.3.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'de.undercouch.download:de.undercouch.download.gradle.plugin:3.3.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

Thanks for your time ! :)

**Comment by Bort-Millipede** [comment] 2017-12-31 21:32
Hello, sorry for the delay.

I have reworked the build script to remove the dependency on third-party module "de.undercouch.download". I have tested it with Gradle 1.4, 2.10, 3.2, and 4.4.1 and built WLT3Serial successfully with all of these versions. Please pull down the latest commit I just submitted and try building again. Take note of the updated commands in the README under "Building".

Another thing to keep in mind in your scenario is that you are using OpenJDK 7 for this. WLT3Serial does not officially support OpenJDK, and only has partial official support for Java 7 in general. If you are able to build WLT3Serial successfully but run into any issues trying to use it, be sure to switch to Oracle JDK 8 instead

Let me know if you run into any more issues. And Happy New Year!

**Comment by syrius01** [comment] 2018-01-03 19:11
Thanks for the update ! I've cloned the new repo, here's the output I'm getting:

sirius@blackb0x:~/sploits/weblogic/WLT3Serial/WLT3Serial-v2$ gradle clean prepare
Starting a Gradle Daemon (subsequent builds will be faster)
Support for running Gradle using Java 7 has been deprecated and is scheduled to be removed in Gradle 5.0. Please see https://docs.gradle.org/4.4.1/userguide/java_plugin.html#sec:java_cross_compilation for more details.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'clean' not found in root project 'WLT3Serial-v2'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s

Thanks for your time!

**Comment by Bort-Millipede** [comment] 2018-01-03 22:34
At first glance, this appears to be a problem with your new gradle installation because I cannot reproduce the error you are seeing. Can you post the output of the ```gradle tasks``` command executed in both the "WLT3Serial" and 'WLT3Serial-v2' directories? The 'clean' task is built-into gradle and is not explicitly defined in the build.gradle file for WLT3Serial.

After getting the outputs of the ```gradle tasks``` commands, I would recommend you do the following:

* Reinstall Gradle 4.4.1 using this tutorial: https://gradle.org/install/#manually
* Remove all cloned WLT3Serial repository directories
* Re-clone the WLT3Serial repository and try building again

Thanks.

**Comment by Bort-Millipede** [comment] 2018-01-06 21:02
Hello again,

I have made a small update to the build script to include the gradle 'base' plugin which should include the 'clean' task in it. Please re-clone the WLT3Serial repository and follow the build instructions. Let me know if everything works. If it does not, I still believe there is an issue with your gradle installation.

Thanks.

**Comment by Bort-Millipede** [comment] 2018-01-17 02:36
Hi syrius01,

I believe all the updates I have made to the build.gradle file should address the issues you were experiencing. Closing this issue for now. If you still experience issues, please open a new issue.

Thanks.

**Closed as completed by Bort-Millipede** 2018-01-17 02:36 UTC
